/**
* \file rcs_kat.h
* \brief <b>RCS Known Answer Tests</b> \n
* New vectors have been added for the extended modes RSX/RCS-256 and RSX/RCS-512, are from the CEX cryptographic library, reference: 
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptographic library</a>
* \author John Underhill
* \date February 02, 2020
*/

#ifndef QSCTEST_RCS_KAT_H
#define QSCTEST_RCS_KAT_H

#include "common.h"

#define CTR_OUTPUT_LENGTH 133
#define MONTE_CARLO_CYCLES 10000
#define RCS_TEST_CYCLES 100

/**
* \brief Tests the RCS 256-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/RCSTest.cpp">CEX RCS tests</a>
*/
bool rcs256_kat_test();

/**
* \brief Tests the RCS 512-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/RCSTest.cpp">CEX RCS tests</a>
*/
bool rcs512_kat_test();

/**
* \brief Tests RCS-256 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool rcs256_stress_test();

/**
* \brief Tests RCS-512 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool rcs512_stress_test();

#endif
