/**
* \file rcs_kat.h
* \brief <b>RCS Known Answer Tests</b> \n
* New vectors have been added for the extended modes RSX/RCS-256 and RSX/RCS-512, are from the CEX cryptographic library, reference: 
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptographic library</a>
* \author John Underhill
* \date October 02, 2020
*/

#ifndef QSCTEST_RCS_TEST_H
#define QSCTEST_RCS_TEST_H

#include "common.h"
#include "rcs.h"

#if defined(QSC_SYSTEM_HAS_AVX512) 
#	if defined(QSC_RCS_AESNI_ENABLED)
#		if !defined(QSC_RCS_AUTHENTICATED)
#			define QSCTEST_RCS_WIDE_BLOCK_TESTS
#		endif
#	endif
#endif

#define QSCTEST_RCS_TEST_CYCLES 100

/**
* \brief Tests the RCS 256-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/RCSTest.cpp">CEX RCS tests</a>
*/
bool qsctest_rcs256_kat();

/**
* \brief Tests the RCS 512-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/RCSTest.cpp">CEX RCS tests</a>
*/
bool qsctest_rcs512_kat();

/**
* \brief Tests RCS-256 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool qsctest_rcs256_stress_test();

/**
* \brief Tests RCS-512 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool qsctest_rcs512_stress_test();

#if defined(QSCTEST_RCS_WIDE_BLOCK_TESTS)
/**
* \brief Tests the RCS AVX functions for equal output to sequential processing.
*
* \return Returns true for success
*/
bool qsctest_rcs_wide_equality();
#endif

/**
* \brief Run all tests.
*/
void qsctest_rcs_run();

#endif
